/**
 * PROJETO DESENVOLVIDO PELA EQUIPE DA MONITORIA - 1903 - CSO BRASILIA F2872117
 * - Elton Macedo Castanho Portela F8369196 - Rafael Shimabukro Borba 
 *
 *
 */
package br.com.bb.view;

import br.com.bb.model.Usuario;
import br.com.bb.splash.SplashScreenApresentacao;
import br.com.bb.suporte.AppUtil;
import br.com.bb.suporte.CorreioDataBase;
import br.com.bb.suporte.PreparaDeskTop;
import java.io.File;
import java.io.IOException;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Equipe Flash Monitoria
 * @date 17/06/2014
 */
public class FormLogin extends javax.swing.JFrame {

    /**
     * Creates new form FormLogin
     */
    public FormLogin() {
        initComponents();
        CorreioDataBase db = new CorreioDataBase();
        db.criaBancoAccess();
        PreparaDeskTop.preparaPastasDesktop();
        if (!new File("Config/sisbb.jks").exists()) {
            AppUtil.preparaPastas();
            AppUtil app = new AppUtil();
            try {
                app.copyFileJar("sisbb.jks",new File("Config/sisbb.jks"));
                app.copyFileJar("sisbb_criptografado.WS" , new File("Config/sisbb_criptografado.WS"));
            } catch (IOException ex) {
                Logger.getLogger(FormLogin.class.getName()).log(Level.SEVERE, null, ex);
            } catch (URISyntaxException ex) {
                Logger.getLogger(FormLogin.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        javax.swing.text.MaskFormatter maskChave = null;

        try{
            maskChave = new javax.swing.text.MaskFormatter("U#######");
            maskChave.setPlaceholderCharacter('_');
        }catch(java.text.ParseException exc){
            JOptionPane.showMessageDialog(null,"Digite a chave correntamente");
        }
        txfChave = new javax.swing.JFormattedTextField(maskChave);
        jLabel2 = new javax.swing.JLabel();
        txfSenha = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        lbCabecalho = new javax.swing.JLabel();
        lbRodape = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PAPELETA DIGITAL");
        setIconImage(new ImageIcon("C:\\Program Files (x86)\\SisBB\\SisBB.gif").getImage());

        jLabel1.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        jLabel1.setText("Login:");

        txfChave.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        jLabel2.setText("Senha:");

        txfSenha.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jButton1.setText("Entrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lbCabecalho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bb/imagens/FaixaBB-2.jpg"))); // NOI18N

        lbRodape.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bb/imagens/FaixaRodape3.jpg"))); // NOI18N

        jMenu1.setText("Utilitario");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bb/imagens/repair-icon.png"))); // NOI18N
        jMenuItem1.setText("Corrigir Banco de dados");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bb/imagens/Actions-help-about-icon.png"))); // NOI18N
        jMenuItem2.setText("Sobre");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbRodape, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(35, 35, 35)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(txfChave, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(txfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(lbCabecalho, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbCabecalho)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txfChave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2))
                    .addComponent(txfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(lbRodape, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setSize(new java.awt.Dimension(275, 331));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        Usuario.setChave(txfChave.getText());
        Usuario.setSenha(new String(txfSenha.getPassword()));
        dispose();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

        CorreioDataBase.corrigirBanco();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed


    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SplashScreenApresentacao apresentacao = new SplashScreenApresentacao(500);
                apresentacao.showSplash();
                try {
                    Thread.sleep(5000);
                    apresentacao.disposeSplash();
                } catch (InterruptedException ex) {
                    Logger.getLogger(FormLogin.class.getName()).log(Level.SEVERE, null, ex);
                }
                new FormLogin().setVisible(true);
            }
        });
    }

    /*
    static {
        try {
            List<Consumidor> listaConsumidores = LeitorXML.lerXMLListaConsumidores("M:\\PUBLICA\\BaseGAT\\Consumidores\\FlashCorreioIDA-V2.xml");
            Consumidor consu = new Consumidor();
            java.net.InetAddress ipInformation = java.net.InetAddress.getLocalHost();
            EscreveXML xml = new EscreveXML();

            if (listaConsumidores != null) {
                for (Consumidor consumidor : listaConsumidores) {
                    if (consumidor.getNome().equals(System.getProperty("user.name")) && consumidor.getIp().equals(ipInformation.toString())) {
                        consu.setNome(consumidor.getNome());
                        consu.setIp(consumidor.getIp());
                        consu.setAcesso(consumidor.isAcesso());
                    }
                }
            }

            if (consu.getNome() == null) {
                System.out.println(">>"+ipInformation.getHostAddress());
                System.out.println(">>"+ipInformation.getHostName());
                System.out.println(">>"+ipInformation.getCanonicalHostName());
                
                
                
                
                if (ipInformation.getHostAddress().substring(0, 10).equals("172.18.246") || ipInformation.getHostAddress().substring(0, 10).equals("172.18.248") || ipInformation.getHostAddress().substring(0, 10).equals("172.18.242") || ipInformation.getHostAddress().substring(0, 10).equals("172.18.244")||ipInformation.getHostAddress().substring(0, 10).equals("192.168.56") ) {
                    consu.setNome(System.getProperty("user.name"));
                    consu.setIp(ipInformation.toString());
                    consu.setAcesso(true);
                    listaConsumidores.add(consu);
                    xml.geraXML(listaConsumidores);
                } else {
                    consu.setNome(System.getProperty("user.name"));
                    consu.setIp(ipInformation.toString());
                    consu.setAcesso(false);
                    listaConsumidores.add(consu);
                    xml.geraXML(listaConsumidores);
                }
            }

            if (!consu.isAcesso()) {
                JOptionPane.showMessageDialog(null, "USUÁRIO : " + System.getProperty("user.name") + "\n\r"
                        + "MAQUINA: " + ipInformation.toString() + "\n\r"
                        + "NÃO POSSUI ACESSO AO ROBO FLASH IDA E SEUS DADOS DE ACESSO FORAM COPIADOS", "Acesso aos dados", JOptionPane.WARNING_MESSAGE);
                System.exit(0);
            }
        } catch (UnknownHostException ex) {
            Logger.getLogger(FormLogin.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JLabel lbCabecalho;
    private javax.swing.JLabel lbRodape;
    private javax.swing.JTextField txfChave;
    private javax.swing.JPasswordField txfSenha;
    // End of variables declaration//GEN-END:variables

}
