/**
 * PROJETO DESENVOLVIDO PELA EQUIPE DA MONITORIA - 1903 - CSO BRASILIA F2872117
 * - Elton Macedo Castanho Portela 
 *
 */
package br.com.bb.view;

import java.awt.Cursor;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author Equipe Flash Monitoria
 * @date 17/06/2014
 */
public class Principal extends javax.swing.JFrame {

    
    FormContrFrameLista formFrameLista;
    FormAlterarPapeleta formAlterarPapeleta;
    FormPapeletaManual formPapeletaManual;
    FormEnviaCorreioPapeleta formEnviaCorreioPapeleta;

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        try {
            Process p = Runtime.getRuntime().exec("java -jar M:\\PUBLICA\\Elton1903\\Bibliotecas\\Mensagens\\FlashMensagens.jar");
        } catch (Exception e) {
        }
        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jButtonManual = new javax.swing.JButton();
        jButtonPesquisar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        jDialog1.setTitle("Descrição sobre o Flash Extrato");

        jLabel3.setText("<html> <body> \t<h3>Robo FrameRiscoUniao</h3> \t<p>Descrição da aplicação:</p> \t- O FrameRiscoUniao A captura informações do Sistama de Informações do \tBanco do Brasil(SISBB), referente à contratos do IDA. \t<hr> \t<p>Instruções de uso:</p> \t<ol> \t\t<li>Preencha o número da agência, contrato, número do gsv e \t\t\tcidade da procuradoria.</li> \t\t<li>Clique em capturar.</li> \t\t<li>Aguarde todas as telas auxiliares fecharem para gerar os \t\t\tDocumentos de captura. \t</ol> \t<hr> \t<p>Instruções sobre o funcionamento do robô:</p> \t<ul> \t\t<li>O robô utiliza os seguintes caminhos para realizar as \t\t\tcapturas das informações.</li> \t\t<ul> \t\t\t<li>Clientes > 01>01&gt;01 Endereços</li> \t\t</ul> \t\t \t\t \t\t<li>Caso o Robo não consiga realizar a elaboração dos relatórios \t\t\tfeche e abra a aplicação novamente clicando apenas no Botão de gerar \t\t\tarquivos, vez que as informações capturadas já estão salvas no Banco \t\t\tde Dados da app.</li> \t\t<li>Caso o robô pare na tela de agência de noticias ou votação \t\t\taperte o botão na aplicação (F3) para que o robô volte ao fluxo \t\t\tnormal de execução em caso de falha.</li> \t\t<li>Caso o robô pare em alguma tela retorne a aplicação para a \t\t\ttela inicial do Sisbb aperte o botão cancelar e capture novamente o \t\t\tas informações.</li> \t\t<li>Caso alguma das telas auxiliares trave feche a aplicação e \t\t\texecute com um número menor operações</li> \t</ul> \t<hr> </body> </html>");

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("FECHAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PAPELETA DIGITAL");
        setIconImage(new ImageIcon("C:\\Program Files (x86)\\SisBB\\SisBB.gif").getImage());
        setResizable(false);

        jToolBar1.setRollover(true);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bb/imagens/notificar.png"))); // NOI18N
        jButton1.setToolTipText("Papeleta Lista");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        jButtonManual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bb/imagens/CadastroManual.jpg"))); // NOI18N
        jButtonManual.setToolTipText("Papeleta Manual");
        jButtonManual.setFocusable(false);
        jButtonManual.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonManual.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonManualActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonManual);

        jButtonPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bb/imagens/Find User Male-52.png"))); // NOI18N
        jButtonPesquisar.setToolTipText("Pesquisar Papeleta");
        jButtonPesquisar.setFocusable(false);
        jButtonPesquisar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonPesquisar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonPesquisar);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bb/imagens/enviar.png"))); // NOI18N
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton3);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bb/imagens/FaixaBB.jpg"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bb/imagens/FaixaRodape.jpg"))); // NOI18N

        jMenu1.setText("Ajuda");

        jMenuItem1.setText("Sobre a Aplicação");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        Cursor cursor = Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR);
        this.setCursor(cursor);

        try {
            mostrarFrameLista();

        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            cursor = Cursor.getDefaultCursor();
            this.setCursor(cursor);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        jDialog1.dispose();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

        java.awt.Dimension tamanhoDialogo = jDialog1.getPreferredSize();
        java.awt.Dimension tamanhoFrame = getSize();
        java.awt.Point loc = getLocation();
        jDialog1.setLocation((tamanhoFrame.width - tamanhoDialogo.width) / 10 + loc.x, (tamanhoFrame.width - tamanhoDialogo.width) / 10 + loc.y);
        jDialog1.setModal(true);
        jDialog1.pack();
        jDialog1.setVisible(true);

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        
        Cursor cursor = Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR);
        this.setCursor(cursor);

        try {
            mostrarFormEnviaCorreio();

        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            cursor = Cursor.getDefaultCursor();
            this.setCursor(cursor);
        }


    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButtonManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonManualActionPerformed

        Cursor cursor = Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR);
        this.setCursor(cursor);

        try {
            mostrarFormPapeletaManual();

        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            cursor = Cursor.getDefaultCursor();
            this.setCursor(cursor);
        }


    }//GEN-LAST:event_jButtonManualActionPerformed

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed

        Cursor cursor = Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR);
        this.setCursor(cursor);

        try {
            mostrarAlterarPesquisarPapeleta();

        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            cursor = Cursor.getDefaultCursor();
            this.setCursor(cursor);
        }


    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    public void mostrarFormPapeletaManual() {
        if (formPapeletaManual == null) {
            formPapeletaManual = new FormPapeletaManual();
            formPapeletaManual.setVisible(true);

        } else {
            formPapeletaManual.setVisible(true);
            formPapeletaManual.setState(JFrame.NORMAL);
        }
    }
    
    public void mostrarFormEnviaCorreio(){
        if (formEnviaCorreioPapeleta == null) {
            formEnviaCorreioPapeleta = new FormEnviaCorreioPapeleta();
            formEnviaCorreioPapeleta.setVisible(true);
            
        } else {
            formEnviaCorreioPapeleta.setVisible(true);
            formEnviaCorreioPapeleta.setState(JFrame.NORMAL);
        }
    }
    

    public void mostrarFrameLista() {
        if (formFrameLista == null) {
            formFrameLista = new FormContrFrameLista();
            formFrameLista.setVisible(true);
        } else {
            formFrameLista.setVisible(true);
            formFrameLista.setState(JFrame.NORMAL);
        }
    }

    public void mostrarAlterarPesquisarPapeleta() {
        if (formAlterarPapeleta == null) {
            formAlterarPapeleta = new FormAlterarPapeleta();
            formAlterarPapeleta.setVisible(true);
        } else {
            formAlterarPapeleta.setVisible(true);
            formAlterarPapeleta.setState(JFrame.NORMAL);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonManual;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables

}
